import { ImageSourcePropType } from 'react-native';

export interface IconName {
  'arrow-down': ImageSourcePropType;
  'arrow-right': ImageSourcePropType;
  back: ImageSourcePropType;
  card: ImageSourcePropType;
  cart: ImageSourcePropType;
  close: ImageSourcePropType;
  dhc: ImageSourcePropType;
  divine: ImageSourcePropType;
  down: ImageSourcePropType;
  next: ImageSourcePropType;
  plus: ImageSourcePropType;
  save: ImageSourcePropType;
  up: ImageSourcePropType;
  lock: ImageSourcePropType;
  facebook: ImageSourcePropType;
  google: ImageSourcePropType;
  apple: ImageSourcePropType;
  exchange: ImageSourcePropType;
  be: ImageSourcePropType;
  instagram: ImageSourcePropType;
  twitter: ImageSourcePropType;
  pinterest: ImageSourcePropType;
  home: ImageSourcePropType;
  'home-fill': ImageSourcePropType;
  categories: ImageSourcePropType;
  'categories-fill': ImageSourcePropType;
  collection: ImageSourcePropType;
  'collection-fill': ImageSourcePropType;
  user: ImageSourcePropType;
  'user-fill': ImageSourcePropType;
  menu: ImageSourcePropType;
  search: ImageSourcePropType;
  notification: ImageSourcePropType;
  heart: ImageSourcePropType;
  diamond: ImageSourcePropType;
  option: ImageSourcePropType;
  column: ImageSourcePropType;
  'column-fill': ImageSourcePropType;
  horizontal: ImageSourcePropType;
  'horizontal-fill': ImageSourcePropType;
  filter: ImageSourcePropType;
  'check-color': ImageSourcePropType;
  share: ImageSourcePropType;
  car: ImageSourcePropType;
  cod: ImageSourcePropType;
  policy: ImageSourcePropType;
  clock: ImageSourcePropType;
  photo: ImageSourcePropType;
  order: ImageSourcePropType;
  phone: ImageSourcePropType;
  location: ImageSourcePropType;
  check: ImageSourcePropType;
  'pick-up': ImageSourcePropType;
  delivered: ImageSourcePropType;
  trash: ImageSourcePropType;
  address: ImageSourcePropType;
  upload: ImageSourcePropType;
  processing: ImageSourcePropType;
  review: ImageSourcePropType;
  cancel: ImageSourcePropType;
  top: ImageSourcePropType;
  bottom: ImageSourcePropType;
  shoes: ImageSourcePropType;
  watches: ImageSourcePropType;
  hat: ImageSourcePropType;
  edit: ImageSourcePropType;
  settings: ImageSourcePropType;
  activity: ImageSourcePropType;
  archive: ImageSourcePropType;
  'qr-code': ImageSourcePropType;
  'log-out': ImageSourcePropType;
  minus: ImageSourcePropType;
  'heart-fill': ImageSourcePropType;
  message: ImageSourcePropType;
}

export const Icons: IconName = {
  'arrow-down': require('./ic_arrow_down.png'),
  'arrow-right': require('./ic_arrow_right.png'),
  back: require('./ic_back.png'),
  card: require('./ic_card.png'),
  cart: require('./ic_cart.png'),
  close: require('./ic_close.png'),
  dhc: require('./ic_dhc.png'),
  divine: require('./ic_divine.png'),
  down: require('./ic_down.png'),
  next: require('./ic_next.png'),
  plus: require('./ic_plus.png'),
  save: require('./ic_save.png'),
  up: require('./ic_up.png'),
  lock: require('./ic_lock.png'),
  facebook: require('./ic_facebook.png'),
  google: require('./ic_google.png'),
  apple: require('./ic_apple.png'),
  exchange: require('./ic_exchange.png'),
  be: require('./ic_be.png'),
  instagram: require('./ic_instagram.png'),
  twitter: require('./ic_twitter.png'),
  pinterest: require('./ic_pinterest.png'),
  home: require('./ic_home.png'),
  'home-fill': require('./ic_home_fill.png'),
  categories: require('./ic_categories.png'),
  'categories-fill': require('./ic_categories_fill.png'),
  collection: require('./ic_collection.png'),
  'collection-fill': require('./ic_collection_fill.png'),
  user: require('./ic_user.png'),
  'user-fill': require('./ic_user_fill.png'),
  menu: require('./ic_menu.png'),
  search: require('./ic_search.png'),
  notification: require('./ic_notification.png'),
  heart: require('./ic_heart.png'),
  diamond: require('./ic_diamond.png'),
  option: require('./ic_option.png'),
  column: require('./ic_column.png'),
  'column-fill': require('./ic_column_fill.png'),
  horizontal: require('./ic_horizontal.png'),
  'horizontal-fill': require('./ic_horizontal_fill.png'),
  filter: require('./ic_filter.png'),
  'check-color': require('./ic_check_color.png'),
  share: require('./ic_share.png'),
  car: require('./ic_car.png'),
  cod: require('./ic_cod.png'),
  policy: require('./ic_policy.png'),
  clock: require('./ic_clock.png'),
  photo: require('./ic_photo.png'),
  order: require('./ic_order.png'),
  phone: require('./ic_phone.png'),
  location: require('./ic_location.png'),
  check: require('./ic_check.png'),
  'pick-up': require('./ic_pick_up.png'),
  delivered: require('./ic_delivered.png'),
  trash: require('./ic_trash.png'),
  address: require('./ic_address.png'),
  upload: require('./ic_upload.png'),
  processing: require('./ic_processing.png'),
  review: require('./ic_review.png'),
  cancel: require('./ic_cancel.png'),
  top: require('./ic_top.png'),
  bottom: require('./ic_bottom.png'),
  shoes: require('./ic_shoes.png'),
  watches: require('./ic_watches.png'),
  hat: require('./ic_hat.png'),
  edit: require('./ic_edit.png'),
  settings: require('./ic_settings.png'),
  activity: require('./ic_activity.png'),
  archive: require('./ic_archive.png'),
  'qr-code': require('./ic_qr.png'),
  'log-out': require('./ic_log_out.png'),
  minus: require('./ic_minus.png'),
  'heart-fill': require('./ic_heart_fill.png'),
  message: require('./ic_message.png'),
};
